security:
  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      anonymous: lazy
      provider: app_user_provider
      guard:
        entry_point: App\Security\LoginFormAuthenticator
        authenticators:
          - App\Security\LoginFormAuthenticator
          - App\Security\GoogleAuthenticator
      logout:
        path: app_logout
        target: app_home

  access_control:
    - { path: '^/admin/users', roles: ROLE_SUPER_ADMIN }
    - { path: '^/admin', roles: ROLE_ADMIN }

  encoders:
    App\Entity\User:
      algorithm: auto

  providers:
    app_user_provider:
      entity:
        class: App\Entity\User
        property: email
