name: homecomb-symfony

type: php:7.4

build:
    flavor: none

# Static website usually don't require much ressources. See
# https://symfony.com/doc/current/cloud/cookbooks/resources_allocation.html
# for more information
size: XS
resources:
    base_memory: 64
    memory_ratio: 128

web:
    commands:
        start: sleep
    locations:
        "/":
            root: "symfony/public"
            index:
                - "index.html"
            scripts: false
            expires: 10m

disk: 256

hooks:
    build: |
        set -x -e

        curl -s https://get.symfony.com/cloud/configurator | (>&2 bash)
        (>&2 symfony-build)
    deploy: |
        set -x -e

        (>&2 symfony-deploy)
