version: '3'

services:
    mailhog:
        image: "mailhog/mailhog:latest"
        container_name: mailhog
        restart: always
        ports:
            - "8025:8025"
            - "1025:1025"
        networks:
            - symfony

volumes:
    db_app:

networks:
    symfony:
